# Site settings
name: sujin
email: sjpark@bitoplus.co.kr
url: http://fghyrg.github.io/
description: "bito test"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: username

twitter:
  username: username